from . import inherit_fl_set_set
from . import inherit_fl_set_voce_organigramma
from . import inherit_registro_giornaliero_configurazione
from . import inherit_sd_dms_document
from . import inherit_sd_protocollo_archivio
from . import inherit_sd_protocollo_cartella
from . import inherit_sd_protocollo_protocollo
from . import inherit_sd_protocollo_registro
from . import inherit_sd_protocollo_registro_emergenza
from . import inherit_sd_protocollo_registro_giornaliero
