from . import account
from . import account_permission
from . import contact
from . import inherit_fetchmail_server
from . import fetchmail_server_history
from . import inherit_ir_mail_server
from . import inherit_mail_thread
from . import inherit_mail_message
from . import inherit_mail_mail
from . import mail_sidebar_item
from . import inherit_res_partner
from . import inherit_res_users