from . import protocollo_registra
from . import protocollo_annulla
from . import protocollo_assegna
from . import protocollo_rifiuta_assegnazione
from . import protocollo_leggi
from . import protocollo_riassegna
from . import protocollo_carica_documento
from . import protocollo_aggiungi_mittente_interno
from . import protocollo_completa_lavorazione
from . import protocollo_rimetti_in_lavorazione
from . import protocollo_elimina_assegnazione
from . import documento_crea_bozza_protocollo
from . import res_config_settings
