from . import protocollo_visibility
from . import protocollo_actions
from . import protocollo_wizard_actions
from . import protocollo_storico_actions
from . import protocollo_permissions
from . import protocollo_filters
from . import inherit_documento_wizard_actions
from . import inherit_documento_permissions
from . import inherit_documento_actions
from . import inherit_document_storico_actions
from . import assegnazione_permissions
from . import assegnazione_wizard_actions
from . import res_config_settings_permissions
from . import invio_permissions
from . import inherit_res_partner_actions
from . import inherit_sd_dms_contact_permissions
from . import protocollo_archivio_actions