{
    "name": "Protocollo",
    "version": "14.0.2.0.0",
    "category": "Document Management",
    "summary": "Protocolla a norma di legge i tuoi documenti",
    "description": """
        APP per la protocollazione informatica dei documenti
    """,
    "author": "Flosslab",
    "website": "https://www.flosslab.com",
    "license": "LGPL-3",
    "sequence": 0,
    "depends": [
        "fl_partner_pec_unique",
        "fl_utility",
        "fl_mail_client_pec",
        "sd_dms",
        "fl_set",
        "fl_m2m_tree",
    ],
    "data": [
        "data/fl_set_set.xml",
        "data/registro.xml",
        "data/mezzo_trasmissione.xml",
        "data/archivio.xml",
        "data/sd_dms_folder.xml",
        "data/inherit_sd_dms_document_type.xml",
        "data/ir_attachment.xml",
        "data/ir_config_parameter.xml",
        "data/ir_cron.xml",
        "data/report_paperformat_landscape.xml",
        "data/report_paperformat_portrait.xml",
        "data/cartella.xml",

        "templates/header_footer_template.xml",
        "templates/registro_giornaliero.xml",

        "reports/registro_giornaliero.xml",

        "security/categories.xml",
        "security/groups.xml",

        "security/access/assegnazione.xml",
        "security/access/invio.xml",
        "security/access/invio_destinatario.xml",
        "security/access/mezzo_trasmissione.xml",
        "security/access/protocollo.xml",
        "security/access/registro.xml",
        "security/access/registro_giornaliero.xml",
        "security/access/registro_emergenza.xml",
        "security/access/registro_emergenza_numero.xml",
        "security/access/archivio.xml",
        "security/access/cartella.xml",
        "security/access/wizard.xml",
        "security/access/ir_actions_act_window.xml",
        "security/access/ir_actions_act_window_view.xml",
        "security/access/registro_giornaliero_configurazione.xml",
        "security/rule/archivio.xml",
        "security/rule/cartella.xml",
        "security/rule/mezzo_trasmissione.xml",
        "security/rule/protocollo.xml",
        "security/rule/registro.xml",
        "security/rule/registro_emergenza.xml",
        "security/rule/registro_giornaliero.xml",

        "actions/protocollo.xml",
        "actions/inherit_sd_dms_documento.xml",

        "menu/action.xml",
        "menu/items.xml",

        "wizards/protocollo_registra.xml",
        "wizards/protocollo_annulla.xml",
        "wizards/protocollo_assegna.xml",
        "wizards/protocollo_rifiuta_assegnazione.xml",
        "wizards/protocollo_completa_lavorazione.xml",
        "wizards/protocollo_riassegna.xml",
        "wizards/protocollo_carica_documento.xml",
        "wizards/protocollo_aggiungi_mittente_interno.xml",
        "wizards/protocollo_leggi.xml",
        "wizards/protocollo_rimetti_in_lavorazione.xml",
        "wizards/protocollo_elimina_assegnazione.xml",
        "wizards/documento_crea_bozza_protocollo.xml",
        "wizards/res_config_settings.xml",

        "views/assegnazione.xml",
        "views/archivio.xml",
        "views/cartella.xml",
        "views/protocollo.xml",
        "views/invio.xml",
        "views/invio_destinatario.xml",
        "views/mezzo_trasmissione.xml",
        "views/registro.xml",
        "views/fl_set_set.xml",
        "views/res_company.xml",
        "views/sd_dms_document.xml",
        "views/sd_dms_document_acl.xml",
        "views/registro_giornaliero.xml",
        "views/registro_emergenza.xml",
        "views/res_partner.xml",
        "views/registro_giornaliero_configurazione.xml",

        "templates/dashboard_template.xml",

        "static/src/templates/web_templates.xml",

    ],
    "qweb": [],
    "installable": True,
    "application": True,
    "post_init_hook": "post_init_hook",
    "auto_install": False
}
