from . import fascicolo_permissions
from . import fascicolo_actions
from . import fascicolo_wizard_actions
from . import fascicolo_storico
from . import inherit_sd_dms_document_actions
from . import inherit_sd_dms_document_wizard_actions
from . import inherit_sd_dms_document_permissions
from . import inherit_res_partner_actions
from . import inherit_sd_dms_document_document_add_contact
from . import InheritSdDmsContactPermissions