from . import archivio
from . import assegnazione
from . import cartella
from . import fl_set_set
from . import fl_set_voce_organigramma
from . import inherit_res_users
from . import inherit_sd_dms_contact
from . import inherit_sd_dms_document_type
from . import invio
from . import invio_destinatario
from . import ir_attachment
from . import mezzo_trasmissione
from . import protocollo
from . import registro
from . import registro_emergenza
from . import registro_emergenza_numero
from . import registro_giornaliero
from . import registro_giornaliero_configurazione
from . import res_company
from . import res_partner
from . import sd_dms_document
from . import sd_dms_document_acl
