from . import inherit_mail_message
from . import inherit_mail_mail
from . import inheirt_mail_thread
from . import inherit_sd_dms_contact
from . import inherit_sd_dms_contact_digital_domicile
from . import inherit_sd_dms_contact_email_address
from . import inherit_sd_protocollo_invio
from . import inherit_sd_protocollo_invio_destinatario
from . import inherit_sd_protocollo_mezzo_trasmissione
from . import inherit_sd_protocollo_protocollo